name: Test on pull request

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout App
          uses: actions/checkout@v4

        - name: Run tests
          run: docker-compose run test pytest